#!/bin/bash

dir="/home/dhanus/Pictures/Wallpapers"
i3config="/home/dhanus/.config/i3/config"
selected=$(sxiv -to $dir/*)
escapedDir=$(echo $selected | sed "s/\//\\\\\//g")

if [ -n $selected ] && [ -f "$selected" ]
then
	sed -ri "s/^exec_always feh --bg-scale.+/exec_always feh --bg-scale $escapedDir/" $i3config \
		&& notify-send -u low -i $selected \
			"Wallpaper changed to $selected" && i3-msg 'restart'
fi
