#!/bin/bash

date=$(date +"%S-%M-%H_%d-%m-%y")
fileName="$date""_Screenshot.jpg"

if [ $# -eq 0 ]
then
	import $HOME/Pictures/Screenshots/$fileName

else
	if [ $1 = 's' ]
	then
		import -window root $HOME/Pictures/Screenshots/$fileName
	fi
fi



